### ISSUE TITLE
Port to MicroPython hits OSError: [Errno 110] ETIMEDOUT

### ISSUE THREAD

**Issue by mdetweiler** [LightWare-Optoelectronics/SampleLibrary#15]
I ported the Raspberry Pi I2C code to run on a Raspberry Pi Pico in MicroPython.  It works, but hits an error after a few cycles through a while loop.  Any idea on improvements to the code or what the issue might be?

```
from machine import Pin, SoftI2C
import time

sda_pin = 26
scl_pin = 27
i2c = SoftI2C(scl=Pin(scl_pin), sda=Pin(sda_pin), freq=100000)

while True:
    reading = i2c.readfrom(102, 0x55, 0)
    dist = reading.hex()[0:4]
    print(dist)
    cm = int(dist, 16)
    inches = 0.394*cm
    feet = 0.0328*cm
    print("The length in inches",round(inches,2))
    print("The length in feet",round(feet,2))
    time.sleep(1.0)
```

After a short run:
```
The length in inches 178.09
The length in feet 14.83
01c4
The length in inches 178.09
The length in feet 14.83
01c4
The length in inches 178.09
The length in feet 14.83
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
OSError: [Errno 110] ETIMEDOUT
```

**Comment by Rob2048** [comment]
Hi @mdetweiler,

I don't have much experience with the Pico running MicroPython so I can't be sure what is causing the issue. It might be related to instabilities on the I2C lines.

Please contact LightWare support and they might be able to point you in the right direction. I am closing the issue here as it is not a direct issue with the sample code.
